version: '3.4'


services:
  postgres:
    container_name: app-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app

volumes:
  postgres-data:

